---

namespace: nagios
name: nagios_xi
version: 0.1.1
readme: README.md
authors:
  - Michael Bellerue (github.com/MikeBellerue-Nagios)
description: A collection of Ansible tools designed for use with Nagios XI.
license_file: LICENSE
tags:
  - nagios
  - monitoring
  - nagiosxi
repository: https://github.com/NagiosEnterprises/automation
homepage: https://github.com/NagiosEnterprises/automation
issues: https://github.com/NagiosEnterprises/automation/issues
build_ignore:
  - .gitignore
