---

namespace: nagios
name: nagios_xi
version: 0.1.3
readme: README.md
authors:
  - Michael Bellerue (github.com/MikeBellerue-Nagios) (github.com/HunnyPuns)
  - Chris Story (github.com/nbkhwjm)
description: A collection of Ansible tools designed for use with Nagios XI.
license_file: LICENSE
tags:
  - nagios
  - monitoring
  - nagiosxi
repository: https://github.com/NagiosEnterprises/automation
homepage: https://github.com/NagiosEnterprises/automation
issues: https://github.com/NagiosEnterprises/automation/issues
build_ignore:
  - '*.tar.gz'
  - '**/__pycache__'
  - .github
  - .gitignore
  - .yamllint
  - tests
  - docs
  - changelogs
  - CHANGELOG.md
  - CONTRIBUTING.md
  - Makefile
